version: '3.7'

services:
  ansible-test:
    build: .
    entrypoint: ["sh", "-c", "ansible-playbook -i hosts --connection=local /app/local.yaml --tags zoxide --skip-tags golang,docker,python,gnome -vvvv && tail -f /dev/null"]
    tty: true
