# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yaml"
  tags: always

- block:
  - include_tasks: gnome.yaml
    when: gnome is defined and gnome == true

  - import_tasks: system-setup.yaml
    tags:
      - package-manager
      - flatpak

  - name: Generate ssh keys
    include_tasks: 
      file: github-ssh-keys/generate-keys.yml
      apply:
        tags:
        - github-ssh-keys
        - ssh
        - system
    loop: "{{ github_accounts }}"
    tags: always

  - import_tasks: github-ssh-keys/add-config.yml

  - name: setup shell
    block:
    - import_tasks: shell-setup/fzf.yaml
    - import_tasks: shell-setup/zoxide.yaml
    - import_tasks: shell-setup/navi.yaml
    - import_tasks: shell-setup/dot-files.yaml
      tags:
        - system-setup
        - dot-files
        - dotfiles
    - import_tasks: shell-setup/oh-my-zsh.yaml
    tags: shell-setup

  - name: install workstation software
    block:
    - import_tasks: software/virtualbox.yaml
    - import_tasks: software/slack.yaml
    - import_tasks: software/flameshot.yaml
    - import_tasks: software/vlc.yaml
    - import_tasks: software/vscode.yaml
      tags:
        - vscode
    tags:
    - software

  rescue:
  - set_fact: task_failed=true