- name: users | milex | install sudo
  tags: 
    - users
    - milex
    - sudo
  package:
    name:
      - sudo
    state: present

- name: users | milex | create group
  tags: 
    - users
    - milex
    - milex-group
  group:
    name: milex
    state: present

- name: users | milex | create user
  tags: 
    - users
    - milex
    - milex-user
  user:
    name: milex
    group: milex
    groups: adm,{{ sudo_group }}
    state: present
    comment: "Milex"
    password: "{{ milex_passwd | password_hash('sha512') }}"
    update_password: on_create
    shell: /bin/bash

- name: users | milex | add sudoers file
  tags: 
  - users
  - milex
  - milex-sudoer
  copy:
    src: users/sudoers_milex
    dest: /etc/sudoers.d/milex
    owner: root
    group: root
    mode: 0440
