- name: base | setup node
  become: yes
  become_flags: -i # Execute config files such as .profile (Ansible uses non-interactive login shells)
  become_user: milex
  block:
    - name: install nvm {{ nvm_version }}
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"

    - name: setup .profile
      ansible.builtin.lineinfile:
        path: ~/.profile
        line: source ~/.nvm/nvm.sh
        create: yes

    - name: install node
      shell: >
        . $HOME/.nvm/nvm.sh && nvm install {{ item }}
      args:
        executable: /bin/bash
        chdir: $HOME
        creates: "$HOME/.nvm/versions/{{ item }}"
      loop:
        - 20.15.0