- name: system setup | utilities | install tmux
  tags: 
    - utilities
    - tmux
  package:
    state: latest
    name: tmux

- name: system setup | utilities | install tmux plugins
  tags:
    - tmux
    - tmux-plugins
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    force: yes
    depth: 1
  become: true
  become_user: milex
  notify: update_tmux_plugin_perms