# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Make sure users exist on the system
  - import_tasks: users/milex.yml
  
  # install packages
  - name: install base packages
    block:
    - import_tasks: software/repositories.yml
    - import_tasks: software/tmux.yml
    - import_tasks: software/packages_dev_py.yml
    - import_tasks: software/packages_golang.yml
    - import_tasks: software/packages_utilities.yml
    tags:
      - packages

  - name: docker installation
    include_tasks: 
      file: "software/packages_docker_{{ ansible_distribution }}.yml"
      apply:
        tags: docker
    when: ansible_distribution == "Ubuntu"
    tags: docker

  # Perform remaining tasks:
  - name: setup base system
    block:
    - import_tasks: system_setup/scripts.yml

    - import_tasks: system_setup/clock.yml
      tags: ntp

    - import_tasks: system_setup/cron.yml
      tags: cron

    - import_tasks: system_setup/locale.yml
      tags: locale

    - import_tasks: system_setup/logging.yml
      tags:
        - logging
        - journald

    - import_tasks: system_setup/openssh-server.yml
      tags: 
        - openssh-server
    tags:
      - system-setup

  rescue:
    - set_fact: task_failed=true
