# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Make sure users exist on the system
  - import_tasks: users/milex.yml
  
  # install software
  - import_tasks: software/repositories.yml
  - import_tasks: software/packages_dev_py.yml
  - import_tasks: software/packages_golang.yml
  - import_tasks: software/packages_utilities.yml

  - name: docker installation
    include_tasks: 
      file: "software/packages_docker_{{ ansible_distribution }}.yml"
      apply:
        tags: docker
    when: ansible_distribution == "Ubuntu"
    tags: always

  # Perform remaining tasks:
  - import_tasks: system_setup/clock.yml
  - import_tasks: system_setup/cron.yml
  - import_tasks: system_setup/locale.yml
  - import_tasks: system_setup/logging.yml
  - import_tasks: system_setup/openssh-server.yml
  - import_tasks: system_setup/scripts.yml

  rescue:
    - set_fact: task_failed=true
